/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example_com_soma_MyNDK */

#ifndef _Included_example_com_soma_MyNDK
#define _Included_example_com_soma_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example_com_soma_MyNDK
 * Method:    addMyFloat
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_example_com_soma_MyNDK_addMyFloat
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     example_com_soma_MyNDK
 * Method:    subMyFloat
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_example_com_soma_MyNDK_subMyFloat
        (JNIEnv *, jobject, jfloat);
#ifdef __cplusplus
}
#endif
#endif
