/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example_com_soma_MyNDK */

#ifndef _Included_example_com_soma_MyNDK
#define _Included_example_com_soma_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example_com_soma_MyNDK
 * Method:    getMyInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_example_com_soma_MyNDK_getMyInt
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
